name: mixpanel
env: {{ ENV }}
listen: "{{HOST|default('0.0.0.0')}}:{{PORT}}"
redis_dsn: "{{REDIS_DSN|default('redis://redis:6379')}}"
rpc_params:
  listen_all: yes
mixpanel_token: "{{MP_TOKEN}}"
endpoint: 'http://api.mixpanel.com/track/'
key_prefix: in.gen.track

